=== imranashraf/partitioner/q2profiling.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/q2profiling" xmlns:tns="http://www.example.org/q2profiling" elementFormDefault="qualified">

    <element name="profiles" type="tns:ProfilesType"></element>
    
    


    


    
    <complexType name="FunctionType">
    	<sequence>
    		<element name="metrics">
    			<complexType>
    				<sequence>
    					<element name="metric" type="tns:MetricType"
    						minOccurs="0" maxOccurs="unbounded">
    					</element>
    				</sequence>
    			</complexType>
    		</element>
    		<element name="statistics">
    			<complexType>
    				<sequence>
    					<element name="measurement"
    						type="tns:MeasurementType" minOccurs="0"
    						maxOccurs="unbounded">
    					</element>
    					<element name="target" type="tns:TargetType"
    						maxOccurs="unbounded" minOccurs="0">
    					</element>
    				</sequence>
    			</complexType>
    		</element>
    		
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="MetricType">
    	<simpleContent>
    		<extension base="double">
    			<attribute name="name" type="string" use="required"></attribute>
    			<attribute name="type" type="string" use="required"></attribute>
    		</extension>
    	</simpleContent>    	
    </complexType>

    <complexType name="MeasurementType">
    	<simpleContent>
    		<extension base="double">
    			<attribute name="unit" type="string"></attribute>
    			    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="type" type="string" use="required"></attribute>
    	<attribute name="by" type="string" use="required"></attribute>
    		</extension>
    	</simpleContent>

    </complexType>

    <complexType name="ChannelType">
    	<sequence>
    		<element name="UnMA" type="int" maxOccurs="1" minOccurs="0"></element>
    		<element name="hUnMA" type="int" maxOccurs="1" minOccurs="0"></element>
    		<element name="bytes" type="int" maxOccurs="1" minOccurs="0"></element>
    		<element name="hBytes" type="int" maxOccurs="1" minOccurs="0"></element>
    		<element name="Values" type="int" maxOccurs="1" minOccurs="0"></element>
    		<element name="hValues" type="int" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    	<attribute name="producer" type="string" use="required"></attribute>
    	<attribute name="consumer" type="string" use="required"></attribute>
    </complexType>

    <complexType name="CallType">
    	<sequence>
    		<element name="calls" type="int" maxOccurs="1" minOccurs="0"></element>
    		<element name="contribution" type="double" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    	<attribute name="caller" type="string" use="required"></attribute>
    	<attribute name="callee" type="string" use="required"></attribute>
    </complexType>

    <complexType name="TargetType">
    	<sequence>
    		<element name="measurement" type="tns:MeasurementType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ApplicationType">
    	<sequence>
    		<element name="location" type="string"></element>
    		<element name="workdir" type="string"></element>
    		<element name="arguments" type="string"></element>
    		<element name="date" type="dateTime"></element>
    		<element name="functions">
    			<complexType>
    				<sequence>
    					<element name="function" type="tns:FunctionType"
    						maxOccurs="unbounded" minOccurs="0">
    					</element>
    				</sequence>
    			</complexType>
    		</element>
    		<element name="QDUGraph">
    			<complexType>
    				<sequence>
    					<element name="channel" type="tns:ChannelType"
    						maxOccurs="unbounded" minOccurs="0">
    					</element>
    				</sequence>
    			</complexType>
    		</element>
    		<element name="CallGraph">
    			<complexType>
    				<sequence>
    					<element name="call" type="tns:CallType"
    						maxOccurs="unbounded" minOccurs="0">
    					</element>
    				</sequence>
    			</complexType>
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="category" type="string"></attribute>
    </complexType>
    


    <complexType name="ProfilesType">
    	<sequence>
    		<element name="application" type="tns:ApplicationType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<anyAttribute></anyAttribute>
    </complexType>
</schema>

=== imranashraf/partitioner/q2profiling.xml
<?xml version="1.0" encoding="UTF-8" ?>
<q2:profiles xmlns:q2="http://www.example.org/q2profiling" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/q2profiling q2profiling.xsd">
    <q2:application name="klt">
    
	<q2:location>/home/rmeeuws/Documents/repository/q2profiling/apps/canny/original/canny</q2:location>
	<q2:workdir>/home/rmeeuws/Documents/repository/q2profiling/apps/canny/original/</q2:workdir>
	<q2:arguments>pics/pic1.pgm 2.0 0.5 0.5</q2:arguments>
	<q2:date>2011-11-16T00:00:00</q2:date>
	<q2:functions>
		<q2:function name="hw_gaussian_nms">
		<q2:metrics>
			<q2:metric name="AICC" type="double">0.100848</q2:metric>
			<q2:metric name="avg_nesting" type="double">0.000000</q2:metric>
		</q2:metrics>
		<q2:statistics>
			<q2:measurement name="hMAR" type="execution" by="QUAD">0.792235451</q2:measurement>
			<q2:target name="Virtex5">
				<q2:measurement name="area" type="prediction" by="Quipu" unit="slices">7034</q2:measurement>
				<q2:measurement name="power" type="prediction" by="Quipu" unit="mW">2289</q2:measurement>
				<q2:measurement name="latency" type="simulation" by="ModelSim" unit="ns">4231009872</q2:measurement>
			</q2:target>			
			<q2:target name="PPC">
				<q2:measurement name="latency" type="execution" by="manual" unit="ns">9011876540</q2:measurement>
				<q2:measurement name="contribution" type="execution" by="MAIP" unit="%">90.34</q2:measurement>
			</q2:target>			
		</q2:statistics>
		</q2:function>
	</q2:functions>    
	
        <q2:QDUGraph>
            <q2:channel producer="pgmRead" consumer="_KLTToFloatImage">
                <q2:hUnMA>9600</q2:hUnMA>
                <q2:hBytes>148800</q2:hBytes>
                <q2:hValues>144000</q2:hValues>
            </q2:channel>
            <q2:channel producer="KLTWriteFeatureListToPPM" consumer="_KLTComputePyramid">
                <q2:hUnMA>4</q2:hUnMA>
                <q2:hBytes>120</q2:hBytes>
                <q2:hValues>4</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTCreateFloatImage" consumer="_interpolate">
                <q2:hUnMA>180</q2:hUnMA>
                <q2:hBytes>16232400</q2:hBytes>
                <q2:hValues>2105</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTCreateFloatImage" consumer="_KLTToFloatImage">
                <q2:hUnMA>24</q2:hUnMA>
                <q2:hBytes>364</q2:hBytes>
                <q2:hValues>340</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTCreateFloatImage" consumer="_convolveSeparate">
                <q2:hUnMA>56</q2:hUnMA>
                <q2:hBytes>1216</q2:hBytes>
                <q2:hValues>645</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTCreateFloatImage" consumer="_convolveImageHoriz">
                <q2:hUnMA>172</q2:hUnMA>
                <q2:hBytes>4144</q2:hBytes>
                <q2:hValues>3217</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTCreateFloatImage" consumer="_KLTComputePyramid">
                <q2:hUnMA>32</q2:hUnMA>
                <q2:hBytes>720</q2:hBytes>
                <q2:hValues>480</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTCreateFloatImage" consumer="_convolveImageVert">
                <q2:hUnMA>252</q2:hUnMA>
                <q2:hBytes>4392</q2:hBytes>
                <q2:hValues>4315</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTToFloatImage" consumer="_KLTToFloatImage">
                <q2:hUnMA>8</q2:hUnMA>
                <q2:hBytes>8</q2:hBytes>
                <q2:hValues>8</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTToFloatImage" consumer="_KLTComputeSmoothedImage">
                <q2:hUnMA>16</q2:hUnMA>
                <q2:hBytes>248</q2:hBytes>
                <q2:hValues>244</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTToFloatImage" consumer="_convolveSeparate">
                <q2:hUnMA>16</q2:hUnMA>
                <q2:hBytes>248</q2:hBytes>
                <q2:hValues>248</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTToFloatImage" consumer="_convolveImageHoriz">
                <q2:hUnMA>38416</q2:hUnMA>
                <q2:hBytes>4821368</q2:hBytes>
                <q2:hValues>595441</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTCreatePyramid" consumer="_KLTComputePyramid">
                <q2:hUnMA>224</q2:hUnMA>
                <q2:hBytes>960</q2:hBytes>
                <q2:hValues>915</q2:hValues>
            </q2:channel>
            <q2:channel producer="_convolveImageHoriz" consumer="_convolveImageVert">
                <q2:hUnMA>148776</q2:hUnMA>
                <q2:hBytes>19034880</q2:hBytes>
                <q2:hValues>2649600</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTComputePyramid" consumer="_interpolate">
                <q2:hUnMA>13772</q2:hUnMA>
                <q2:hBytes>3924000</q2:hBytes>
                <q2:hValues>96648</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTComputePyramid" consumer="_convolveImageHoriz">
                <q2:hUnMA>57600</q2:hUnMA>
                <q2:hBytes>7459200</q2:hBytes>
                <q2:hValues>576000</q2:hValues>
            </q2:channel>
            <q2:channel producer="_convolveImageVert" consumer="_interpolate">
                <q2:hUnMA>41692</q2:hUnMA>
                <q2:hBytes>11980800</q2:hBytes>
                <q2:hValues>316776</q2:hValues>
            </q2:channel>
            <q2:channel producer="_convolveImageVert" consumer="_convolveImageHoriz">
                <q2:hUnMA>57600</q2:hUnMA>
                <q2:hBytes>5792640</q2:hBytes>
                <q2:hValues>595200</q2:hValues>
            </q2:channel>
            <q2:channel producer="_convolveImageVert" consumer="_KLTComputePyramid">
                <q2:hUnMA>38400</q2:hUnMA>
                <q2:hBytes>576000</q2:hBytes>
                <q2:hValues>576000</q2:hValues>
            </q2:channel>
            <q2:channel producer="_convolveImageVert" consumer="_KLTFreeFloatImage">
                <q2:hUnMA>23968</q2:hUnMA>
                <q2:hBytes>835200</q2:hBytes>
                <q2:hValues>153568</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTFreeFloatImage" consumer="_interpolate">
                <q2:hUnMA>7844</q2:hUnMA>
                <q2:hBytes>5738400</q2:hBytes>
                <q2:hValues>61760</q2:hValues>
            </q2:channel>
            <q2:channel producer="_KLTFreeFloatImage" consumer="_convolveImageHoriz">
                <q2:hUnMA>14400</q2:hUnMA>
                <q2:hBytes>1713600</q2:hBytes>
                <q2:hValues>144000</q2:hValues>
            </q2:channel>
            <q2:channel producer="UNKNOWN_PRODUCER(CONSTANT_DATA)" consumer="_createArray2D.clone.0">
                <q2:hUnMA>8</q2:hUnMA>
                <q2:hBytes>8</q2:hBytes>
                <q2:hValues>8</q2:hValues>
            </q2:channel>
            <q2:channel producer="UNKNOWN_PRODUCER(CONSTANT_DATA)" consumer="_minEigenvalue">
                <q2:hUnMA>8</q2:hUnMA>
                <q2:hBytes>3072</q2:hBytes>
                <q2:hValues>8</q2:hValues>
            </q2:channel>
            <q2:channel producer="UNKNOWN_PRODUCER(CONSTANT_DATA)" consumer="_printShutdown">
                <q2:hUnMA>12</q2:hUnMA>
                <q2:hBytes>12</q2:hBytes>
                <q2:hValues>4</q2:hValues>
            </q2:channel>
            <q2:channel producer="UNKNOWN_PRODUCER(CONSTANT_DATA)" consumer="Out_of_the_main_function_scope">
                <q2:hUnMA>20229</q2:hUnMA>
                <q2:hBytes>29758</q2:hBytes>
                <q2:hValues>20229</q2:hValues>
            </q2:channel>
            <q2:channel producer="UNKNOWN_PRODUCER(CONSTANT_DATA)" consumer="pgmReadFile">
                <q2:hUnMA>347</q2:hUnMA>
                <q2:hBytes>1422</q2:hBytes>
                <q2:hValues>382</q2:hValues>
            </q2:channel>
            <q2:channel producer="UNKNOWN_PRODUCER(CONSTANT_DATA)" consumer="_printSetupBin">
                <q2:hUnMA>16</q2:hUnMA>
                <q2:hBytes>17</q2:hBytes>
                <q2:hValues>13</q2:hValues>
            </q2:channel>
            <q2:channel producer="UNKNOWN_PRODUCER(CONSTANT_DATA)" consumer="_start">
                <q2:hUnMA>154</q2:hUnMA>
                <q2:hBytes>197</q2:hBytes>
                <q2:hValues>154</q2:hValues>
            </q2:channel>
            <q2:channel producer="UNKNOWN_PRODUCER(CONSTANT_DATA)" consumer="pgmRead">
                <q2:hUnMA>12296</q2:hUnMA>
                <q2:hBytes>14411</q2:hBytes>
                <q2:hValues>12296</q2:hValues>
            </q2:channel>
            <q2:channel producer="UNKNOWN_PRODUCER(CONSTANT_DATA)" consumer="_enforceMinimumDistance">
                <q2:hUnMA>140</q2:hUnMA>
                <q2:hBytes>182</q2:hBytes>
                <q2:hValues>140</q2:hValues>
            </q2:channel>
            <q2:channel producer="UNKNOWN_PRODUCER(CONSTANT_DATA)" consumer="KLTFreeFeatureTable">
                <q2:hUnMA>20</q2:hUnMA>
                <q2:hBytes>32</q2:hBytes>
                <q2:hValues>16</q2:hValues>
            </q2:channel>
            <q2:channel producer="UNKNOWN_PRODUCER(CONSTANT_DATA)" consumer="_init">
                <q2:hUnMA>4</q2:hUnMA>
                <q2:hBytes>4</q2:hBytes>
                <q2:hValues>4</q2:hValues>
            </q2:channel>
            <q2:channel producer="UNKNOWN_PRODUCER(CONSTANT_DATA)" consumer="pnmReadHeader">
                <q2:hUnMA>318</q2:hUnMA>
                <q2:hBytes>1779</q2:hBytes>
                <q2:hValues>318</q2:hValues>
            </q2:channel>
            <q2:channel producer="UNKNOWN_PRODUCER(CONSTANT_DATA)" consumer="__do_global_ctors_aux">
